/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.chart.PieChart;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author johnn
 */
public class Agenda extends javax.swing.JFrame {
    int AnoFixo = 0, MesFixo = 0, DiaFixo = 0;
    int AnoAltera = 0, MesAltera = 0, DiaAltera = 0;
    int valorselecao = 0;

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        IniciarCalendario();
        Calendario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        SelecaoMes = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jLabelDom = new javax.swing.JLabel();
        jPanelDom = new javax.swing.JPanel();
        t1 = new javax.swing.JLabel();
        t8 = new javax.swing.JLabel();
        t15 = new javax.swing.JLabel();
        t22 = new javax.swing.JLabel();
        t29 = new javax.swing.JLabel();
        t36 = new javax.swing.JLabel();
        jPanelSeg = new javax.swing.JPanel();
        t2 = new javax.swing.JLabel();
        t9 = new javax.swing.JLabel();
        t16 = new javax.swing.JLabel();
        t23 = new javax.swing.JLabel();
        t30 = new javax.swing.JLabel();
        t37 = new javax.swing.JLabel();
        jPanelTer = new javax.swing.JPanel();
        t3 = new javax.swing.JLabel();
        t10 = new javax.swing.JLabel();
        t17 = new javax.swing.JLabel();
        t24 = new javax.swing.JLabel();
        t31 = new javax.swing.JLabel();
        t38 = new javax.swing.JLabel();
        jPanelDom3 = new javax.swing.JPanel();
        t4 = new javax.swing.JLabel();
        t11 = new javax.swing.JLabel();
        t18 = new javax.swing.JLabel();
        t25 = new javax.swing.JLabel();
        t32 = new javax.swing.JLabel();
        t39 = new javax.swing.JLabel();
        jPanelDom4 = new javax.swing.JPanel();
        t5 = new javax.swing.JLabel();
        t12 = new javax.swing.JLabel();
        t19 = new javax.swing.JLabel();
        t26 = new javax.swing.JLabel();
        t33 = new javax.swing.JLabel();
        t40 = new javax.swing.JLabel();
        jPanelDom5 = new javax.swing.JPanel();
        t6 = new javax.swing.JLabel();
        t13 = new javax.swing.JLabel();
        t20 = new javax.swing.JLabel();
        t27 = new javax.swing.JLabel();
        t34 = new javax.swing.JLabel();
        t41 = new javax.swing.JLabel();
        jPanelDom6 = new javax.swing.JPanel();
        t7 = new javax.swing.JLabel();
        t14 = new javax.swing.JLabel();
        t21 = new javax.swing.JLabel();
        t28 = new javax.swing.JLabel();
        t35 = new javax.swing.JLabel();
        t42 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        SelecaoAno = new javax.swing.JComboBox<>();
        AnoPag1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane2.setToolTipText("");

        SelecaoMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        jLabelDom.setBackground(new java.awt.Color(51, 153, 255));
        jLabelDom.setText("Dom");

        t1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t1.setText("0");

        t8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t8.setText("0");

        t15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t15.setText("0");

        t22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t22.setText("0");

        t29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t29.setText("0");

        t36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t36.setText("0");

        javax.swing.GroupLayout jPanelDomLayout = new javax.swing.GroupLayout(jPanelDom);
        jPanelDom.setLayout(jPanelDomLayout);
        jPanelDomLayout.setHorizontalGroup(
            jPanelDomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDomLayout.setVerticalGroup(
            jPanelDomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t36)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        t2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t2.setText("0");

        t9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t9.setText("0");

        t16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t16.setText("0");

        t23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t23.setText("0");

        t30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t30.setText("0");

        t37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t37.setText("0");

        javax.swing.GroupLayout jPanelSegLayout = new javax.swing.GroupLayout(jPanelSeg);
        jPanelSeg.setLayout(jPanelSegLayout);
        jPanelSegLayout.setHorizontalGroup(
            jPanelSegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSegLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelSegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSegLayout.setVerticalGroup(
            jPanelSegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSegLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t37)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        t3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t3.setText("0");

        t10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t10.setText("0");

        t17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t17.setText("0");

        t24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t24.setText("0");

        t31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t31.setText("0");

        t38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t38.setText("0");

        javax.swing.GroupLayout jPanelTerLayout = new javax.swing.GroupLayout(jPanelTer);
        jPanelTer.setLayout(jPanelTerLayout);
        jPanelTerLayout.setHorizontalGroup(
            jPanelTerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTerLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelTerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTerLayout.setVerticalGroup(
            jPanelTerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t38)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        t4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t4.setText("0");

        t11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t11.setText("0");

        t18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t18.setText("0");

        t25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t25.setText("0");

        t32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t32.setText("0");

        t39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t39.setText("0");

        javax.swing.GroupLayout jPanelDom3Layout = new javax.swing.GroupLayout(jPanelDom3);
        jPanelDom3.setLayout(jPanelDom3Layout);
        jPanelDom3Layout.setHorizontalGroup(
            jPanelDom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDom3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelDom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDom3Layout.setVerticalGroup(
            jPanelDom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDom3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t39)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        t5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t5.setText("0");

        t12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t12.setText("0");

        t19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t19.setText("0");

        t26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t26.setText("0");

        t33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t33.setText("0");

        t40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t40.setText("0");

        javax.swing.GroupLayout jPanelDom4Layout = new javax.swing.GroupLayout(jPanelDom4);
        jPanelDom4.setLayout(jPanelDom4Layout);
        jPanelDom4Layout.setHorizontalGroup(
            jPanelDom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDom4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelDom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDom4Layout.setVerticalGroup(
            jPanelDom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDom4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t40)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        t6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t6.setText("0");

        t13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t13.setText("0");

        t20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t20.setText("0");

        t27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t27.setText("0");

        t34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t34.setText("0");

        t41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t41.setText("0");

        javax.swing.GroupLayout jPanelDom5Layout = new javax.swing.GroupLayout(jPanelDom5);
        jPanelDom5.setLayout(jPanelDom5Layout);
        jPanelDom5Layout.setHorizontalGroup(
            jPanelDom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDom5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelDom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDom5Layout.setVerticalGroup(
            jPanelDom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDom5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t41)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        t7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t7.setText("0");

        t14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t14.setText("0");

        t21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t21.setText("0");

        t28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t28.setText("0");

        t35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t35.setText("0");

        t42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t42.setText("0");

        javax.swing.GroupLayout jPanelDom6Layout = new javax.swing.GroupLayout(jPanelDom6);
        jPanelDom6.setLayout(jPanelDom6Layout);
        jPanelDom6Layout.setHorizontalGroup(
            jPanelDom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDom6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelDom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t42, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDom6Layout.setVerticalGroup(
            jPanelDom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDom6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t42)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setText("Seg");

        jLabel62.setText("Ter");

        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Qua");

        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("Qui");
        jLabel64.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel64.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel64.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("Sex");
        jLabel65.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Sáb");

        SelecaoAno.setEditable(true);

        jLayeredPane2.setLayer(SelecaoMes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jSpinner1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabelDom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanelDom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanelSeg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanelTer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanelDom3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanelDom4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanelDom5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanelDom6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel62, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel63, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel64, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel65, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel66, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(SelecaoAno, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(0, 112, Short.MAX_VALUE)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(jPanelTer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(jLabel62)
                                .addGap(29, 29, 29)))
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDom3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelDom4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelDom5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelDom6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(SelecaoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane2Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jPanelDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelDom))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SelecaoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jPanelSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelecaoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelecaoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDom)
                    .addComponent(jLabel1)
                    .addComponent(jLabel62)
                    .addComponent(jLabel63)
                    .addComponent(jLabel64)
                    .addComponent(jLabel65)
                    .addComponent(jLabel66))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AnoPag1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        AnoPag1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AnoPag1.setText("2021");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Quarta");

        jLayeredPane1.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(AnoPag1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(AnoPag1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel3)))
                .addContainerGap(552, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(AnoPag1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(331, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
            try {
                  UIManager.setLookAndFeel("com.formdev.flatlaf.FlatIntelliJLaf");
              } catch (ClassNotFoundException ex) {
                  Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
              } catch (InstantiationException ex) {
                 Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
              } catch (IllegalAccessException ex) {
                 Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
              } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnoPag1;
    private javax.swing.JComboBox<String> SelecaoAno;
    private javax.swing.JComboBox<String> SelecaoMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabelDom;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanelDom;
    private javax.swing.JPanel jPanelDom3;
    private javax.swing.JPanel jPanelDom4;
    private javax.swing.JPanel jPanelDom5;
    private javax.swing.JPanel jPanelDom6;
    private javax.swing.JPanel jPanelSeg;
    private javax.swing.JPanel jPanelTer;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t10;
    private javax.swing.JLabel t11;
    private javax.swing.JLabel t12;
    private javax.swing.JLabel t13;
    private javax.swing.JLabel t14;
    private javax.swing.JLabel t15;
    private javax.swing.JLabel t16;
    private javax.swing.JLabel t17;
    private javax.swing.JLabel t18;
    private javax.swing.JLabel t19;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t20;
    private javax.swing.JLabel t21;
    private javax.swing.JLabel t22;
    private javax.swing.JLabel t23;
    private javax.swing.JLabel t24;
    private javax.swing.JLabel t25;
    private javax.swing.JLabel t26;
    private javax.swing.JLabel t27;
    private javax.swing.JLabel t28;
    private javax.swing.JLabel t29;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t30;
    private javax.swing.JLabel t31;
    private javax.swing.JLabel t32;
    private javax.swing.JLabel t33;
    private javax.swing.JLabel t34;
    private javax.swing.JLabel t35;
    private javax.swing.JLabel t36;
    private javax.swing.JLabel t37;
    private javax.swing.JLabel t38;
    private javax.swing.JLabel t39;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t40;
    private javax.swing.JLabel t41;
    private javax.swing.JLabel t42;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t7;
    private javax.swing.JLabel t8;
    private javax.swing.JLabel t9;
    // End of variables declaration//GEN-END:variables
    public void IniciarCalendario(){
        SimpleDateFormat Ano = new SimpleDateFormat("yyyy");
        SimpleDateFormat Mes = new SimpleDateFormat("MM");  
        SimpleDateFormat Dia = new SimpleDateFormat("dd");
        
        AnoFixo = Integer.parseInt(Ano.format(new Date()));
        MesFixo = Integer.parseInt(Mes.format(new Date()));
        DiaFixo = Integer.parseInt(Dia.format(new Date()));
        
        //JOptionPane.showMessageDialog(null, DiaFixo + "/" + MesFixo + "/" + AnoFixo);
        
        int AnoMaximo = AnoFixo + 50;
        for (int i = 2000; i < AnoMaximo; i++){
           String AnoString = Integer.toString(i);
            SelecaoAno.addItem(AnoString);
        }
        
        SelecaoAno.setSelectedItem(AnoFixo);
        
        
        
        if (MesFixo ==1){
            SelecaoMes.setSelectedIndex(0);
        }else if (MesFixo == 2){
            SelecaoMes.setSelectedIndex(1);
        }else if (MesFixo == 3){
            SelecaoMes.setSelectedIndex(2);
        }else if (MesFixo == 4){
            SelecaoMes.setSelectedIndex(3);
        }else if (MesFixo == 5){
            SelecaoMes.setSelectedIndex(4);
        }else if (MesFixo == 6){
            SelecaoMes.setSelectedIndex(5);
        }else if (MesFixo == 7){
            SelecaoMes.setSelectedIndex(6);
        }else if (MesFixo == 8){
            SelecaoMes.setSelectedIndex(7);
        }
        else if (MesFixo == 9){
            SelecaoMes.setSelectedIndex(8);
        }else if (MesFixo == 10){
            SelecaoMes.setSelectedIndex(9);
        }else if (MesFixo == 11){
            SelecaoMes.setSelectedIndex(10);
        }else if (MesFixo == 12){
            SelecaoMes.setSelectedIndex(11);
        }
        }
    public void Calendario (){
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        t7.setText("");
        t8.setText("");
        t9.setText("");
        t10.setText("");
        t11.setText("");
        t12.setText("");
        t13.setText("");
        t14.setText("");
        t15.setText("");
        t16.setText("");
        t17.setText("");
        t18.setText("");
        t19.setText("");
        t20.setText("");
        t21.setText("");
        t22.setText("");
        t23.setText("");
        t24.setText("");
        t25.setText("");
        t26.setText("");
        t27.setText("");
        t28.setText("");
        t29.setText("");
        t30.setText("");
        t31.setText("");
        t32.setText("");
        t33.setText("");
        t34.setText("");
        t35.setText("");
        t36.setText("");
        t37.setText("");
        t38.setText("");
        t39.setText("");
        t40.setText("");
        t41.setText("");
        t42.setText("");
        
        
        DiaAltera = DiaFixo;
        MesAltera = SelecaoMes.getSelectedIndex();
        AnoAltera = Integer.parseInt(SelecaoAno.getSelectedItem().toString());
        
        int TotalDiasMes = 0;
        
        if(MesAltera == 0){
            TotalDiasMes = 31;
        }else if (MesAltera == 1){
            int resultado = (AnoAltera % 4);
            if (resultado == 0){
                TotalDiasMes = 29;
            }else{
                TotalDiasMes = 28;
            }  
    }
        else if (MesAltera == 2){
            TotalDiasMes = 31;
        }
        else if (MesAltera == 3){
            TotalDiasMes = 30;
        }
        else if (MesAltera == 4){
            TotalDiasMes = 31;
        }
        else if (MesAltera == 5){
            TotalDiasMes = 30;
        }
        else if (MesAltera == 6){
            TotalDiasMes = 31;
        }
        else if (MesAltera == 7){
            TotalDiasMes = 31;
        }
        else if (MesAltera == 8){
            TotalDiasMes = 30;
        }
        else if (MesAltera == 9){
            TotalDiasMes = 31;
        }
        else if (MesAltera == 10){
            TotalDiasMes = 30;
        }
        else if (MesAltera == 11){
            TotalDiasMes = 31;
        }
        Calendar calendar = Calendar.getInstance();
        calendar.set(AnoAltera, MesAltera, 1);
        int SetaDia = 0;
        
        int Semana = calendar.get(Calendar.DAY_OF_WEEK);
        if(Semana == Calendar.SUNDAY){
            SetaDia = 1;
            System.out.println("Dom");
        } else if (Semana == Calendar.MONDAY){
            SetaDia = 2;
            System.out.println("Seg");
        } else if (Semana == Calendar.TUESDAY){
            SetaDia = 3;
            System.out.println("Ter");
        } else if (Semana == Calendar.WEDNESDAY){
            SetaDia = 4;
            System.out.println("Qua");
        } else if (Semana == Calendar.THURSDAY){
            SetaDia = 5;
            System.out.println("Qui");
        } else if (Semana == Calendar.FRIDAY){
            SetaDia = 6;
            System.out.println("Sex");
        } else if (Semana == Calendar.SATURDAY){
            SetaDia = 7;
            System.out.println("Sáb");
        }
        
            for (int i = 1; i <= TotalDiasMes; i++){
                switch (SetaDia){
                    case 1:
                        t1.setText("" + i);
                        break;
                    case 2:
                        t2.setText("" + i);
                        if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t2.setForeground(Color.red);
                        }else{
                            t2.setForeground(Color.black);
                        }
                        break;
                    case 3:
                        t3.setText("" + i);
                         if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t3.setForeground(Color.red);
                        }else{
                            t3.setForeground(Color.black);
                        }
                        break;
                    case 4:
                        t4.setText("" + i);
                         if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t4.setForeground(Color.red);
                        }else{
                            t4.setForeground(Color.black);
                        }
                        break;
                    case 5:
                        t5.setText("" + i);
                         if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t5.setForeground(Color.red);
                        }else{
                            t5.setForeground(Color.black);
                        }
                        break;
                    case 6:
                        t6.setText("" + i);
                         if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t6.setForeground(Color.red);
                        }else{
                            t6.setForeground(Color.black);
                        }
                        break;
                    case 7:
                        t7.setText("" + i);
                         if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t7.setForeground(Color.red);
                        }else{
                            t7.setForeground(Color.black);
                        }
                        break;
                    case 8:
                        t8.setText("" + i);
                         if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t8.setForeground(Color.red);
                        }else{
                            t8.setForeground(Color.black);
                        }
                        break;
                    case 9:
                        t9.setText("" + i);
                         if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t9.setForeground(Color.red);
                        }else{
                            t9.setForeground(Color.black);
                        }
                        break;
                    case 10:
                        t10.setText("" + i);
                         if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t10.setForeground(Color.red);
                        }else{
                            t10.setForeground(Color.black);
                        }
                        break;
                    case 11:
                        t11.setText("" + i);
                         if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t11.setForeground(Color.red);
                        }else{
                            t11.setForeground(Color.black);
                        }
                        break;   
                    case 12:
                        t12.setText("" + i);
                        if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t12.setForeground(Color.red);
                        }else{
                            t12.setForeground(Color.black);
                        }
                        break;
                    case 13:
                        t13.setText("" + i);
                        if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t13.setForeground(Color.red);
                        }else{
                            t13.setForeground(Color.black);
                        }
                        break; 
                    case 14:
                        t14.setText("" + i);
                        if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t14.setForeground(Color.red);
                        }else{
                            t14.setForeground(Color.black);
                        }
                        break;
                    case 15:
                        t15.setText("" + i);
                        if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t15.setForeground(Color.red);
                        }else{
                            t15.setForeground(Color.black);
                        }
                        break;
                    case 16:
                        t16.setText("" + i);
                        if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t16.setForeground(Color.red);
                        }else{
                            t16.setForeground(Color.black);
                        }
                        break;    
                    case 17:
                        t17.setText("" + i);
                        if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t17.setForeground(Color.red);
                        }else{
                            t17.setForeground(Color.black);
                        }
                        break;
                    case 18:
                        t18.setText("" + i);
                        if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t18.setForeground(Color.red);
                        }else{
                            t18.setForeground(Color.black);
                        }
                    case 19:
                        t19.setText("" + i);
                        if(i == DiaFixo & MesAltera == MesFixo - 1 & AnoAltera == AnoFixo){
                            t19.setForeground(Color.red);
                        }else{
                            t19.setForeground(Color.black);
                        }
                        break;
                    case 20:
                        t20.setText("" + i);
                        break;
                    case 21:
                        t21.setText("" + i);
                        break;
                    case 22:
                        t22.setText("" + i);
                        break;
                    case 23:
                        t23.setText("" + i);
                        break;   
                    case 24:
                        t24.setText("" + i);
                        break; 
                    case 25:
                        t25.setText("" + i);
                        break; 
                    case 26:
                        t26.setText("" + i);
                        break;  
                    case 27:
                        t27.setText("" + i);
                        break; 
                    case 28:
                        t28.setText("" + i);
                        break;    
                    case 29:
                        t29.setText("" + i);
                        break; 
                    case 30:
                        t30.setText("" + i);
                        break;
                    case 31:
                        t30.setText("" + i);
                        break;
                    case 32:
                        t32.setText("" + i);
                        break;  
                    case 33:
                        t33.setText("" + i);
                        break;  
                    case 34:
                        t34.setText("" + i);
                        break;
                    case 35:
                        t35.setText("" + i);
                        break;
                    case 36:
                        t36.setText("" + i);
                        break;
                    case 37:
                        t37.setText("" + i);
                        break;
                    case 38:
                        t38.setText("" + i);
                        break;
                    case 39:
                        t39.setText("" + i);
                        break;
                    case 40:
                        t40.setText("" + i);
                        break;
                    case 41:
                        t41.setText("" + i);
                        break; 
                    case 42:
                        t42.setText("" + i);
                        break;     
                }
                SetaDia ++;
            }
    }
}
